source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks! :linkage => :static

inhibit_all_warnings!
install! 'cocoapods',
            :generate_multiple_pod_projects => true,
            :incremental_installation => true


target 'SwiftDemo' do

  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'ObjectMapper', '~> 4.2.0'
  
end

